# bot基本配置
Master: Master
Admins: []
bot_accounts: []
default_account: default_account
GroupMsg_log: true
test_group: test_group
proxy: proxy

# mah配置
mirai_host: http://localhost:8080
verify_key: verify_key

# 数据库连接地址
db_link: sqlite+aiosqlite:///data.db

# 日志信息
log_related:
  common_retention: 7
  error_retention: 14

# 其他功能配置信息
bf1:
  default_account: default_account