# 基本配置
Master: 主人qq
Admins: []
bot_accounts: [bot账号列表]
default_account: 默认bot账号
off_bots: []
bot_blocked: []
mirai_host: 你的mah配置例子如:http://localhost:8080
verify_key: 你的verify_key
test_group: 测试群群号-用于发送通知等
vip_group: []
black_group: []
db_link: 数据库地址,默认为sqlite+aiosqlite:///data.db
proxy: proxy

# 日志相关
log_related:
  error_retention: 14
  common_retention: 7

# 战地一配置
bf1:
  default_account: 账号pid

# chatGPT配置
openai_cookie: openai_cookie
