# 基本配置
Master: 1257661006
Admins: []
bot_accounts: [2417999374]
default_account: 000
off_bots: []
bot_blocked: []
mirai_host: http://localhost:8080
verify_key: SBXMMX
test_group: 1090153034
vip_group: []
black_group: []
db_link: sqlite+aiosqlite:///data.db
proxy: proxy

# 日志相关
log_related:
  error_retention: 14
  common_retention: 7

# 战地一配置
bf1:
  default_account: 123

# chatGPT配置
openai_cookie: abc