[tool.poetry]
name = "bot-xiaomai-open"
version = "0.3.0"
description = "基于Graia-Ariadne开的qqbot-小埋，v3重构版本"
authors = ["13"]
license = "GNU GENERAL PUBLIC LICENSE"
readme = "README.md"
packages = [{include = "bot_xiaomai_open"}]

[tool.poetry.dependencies]
python = "3.10"
httpx = "^0.23.1"
creart = "^0.2.2"
graia-ariadne = {extras = ["standard"], version = "^0.10.2"}
graiax-playwright = "^0.2.1"
sqlalchemy = "^1.4.45"
pyyaml = "^6.0"
aiosqlite = "^0.18.0"
psutil = "^5.9.4"
arclet-alconna-graia = "^0.10.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[[tool.poetry.source]]
name = "tuna-tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = false
