botinfo:
  Admin:
  - 000
  Master: 000
  bot:
  - 2417999374
  offbot:
  - 000
  bot_blocked:
    - 000
  mah: http://localhost:8080
  verifyKey: SBXMMX
  testgroup: 000
vipgroup:
  - 000
bf1:
  default_account: 000
