botinfo:
  Admin:
  - 000
  Master: 1257661006
  bot:
  - 2417999374
  offbot:
  - 000
  bot_blocked:
    - 000
  mah: http://localhost:8080
  verifyKey: SBXMMX
  testgroup: 749094683
vipgroup:
  - 000
bf1:
  default_account: 000
