funlist_on:
- test
- 入群审核
- bf1服管
- bf1战绩
- 龙图撤回
- 识图
- 头像表情包
- 群管
- 复读机
- logo生成
- 塔罗牌
- 搜种子
- 猜单词
- 词云
- 原神角色卡
- 天气查询
- 哔哩哔哩订阅
- APEX查询
- emoji融合
- 小埋说
- AI绘画
funlist_off: []
funlist_always:
- perm
- switch
366012221:
- bf1战绩
- bf1服管
- test
1090153034:
- test
- bf1战绩
- bf1服管
- 入群审核
- 龙图撤回
- 识图
- 头像表情包
- 群管
- 复读机
- logo生成
- 搜种子
- 猜单词
- 词云
- 原神角色卡
- 天气查询
- 哔哩哔哩订阅
- APEX查询
- emoji融合
- 小埋说
- AI绘画
278698466:
- bf1战绩
995159101:
- bf1战绩
- 群管
749094683: []
1073065602: []
