funlist_on:
- test
- 入群审核
- bf1服管
- bf1战绩
- 龙图撤回
- 识图
funlist_off: []
funlist_always:
- perm
- switch
366012221:
- bf1战绩
- bf1服管
- test
1090153034:
- test
- bf1战绩
- bf1服管
- 入群审核
- 龙图撤回
- 识图
278698466:
- bf1战绩
995159101:
- bf1战绩
